### ISSUE TITLE
I have problems, in executing the code. Can i get some more guidance on running the code

### ISSUE THREAD

**Issue by devasenan134** [leVirve/lsun-room#29]
Can you guide me through, running this code in my local Jupyter notebook from start to end.

**Comment by HardikJain02** [comment]
Follow this! After this you might get error if you are running on cloud machine. (related to displaying the result, download the result instead)

```
git clone https://github.com/leVirve/lsun-room.git
conda create --name lsun
conda activate lsun
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip install -r requirements.txt [remove versions from requirements.txt]
mkdir checkpoint
cd checkpoint
gdown https://drive.google.com/uc?id=1aUJoXM9SQMe0LC38pA8v8r43pPOAaQ-a
cd ..
pip install loguru
cd trainer
git clone https://github.com/leVirve/OneGan.git
cd OneGan
pip install -e .
cd ..
cd ..
run this: python demo.py image --weight {checkpoint_path} --path {image_filepath}
```

**Comment by BytDance** [comment]
I did all that on windows which went well without any error, but when I ran "python demo.py image --weight {checkpoint_path} --path {image_filepath}" 

I got this error 

```
Usage: demo.py image [OPTIONS]
Try 'demo.py image --help' for help.

Error: Invalid value for '--weight': Path '{checkpoint_path}' does not exist.
```

**Comment by HardikJain02** [comment]
you need to actually put the real path to the checkpoint and image file path

**Comment by BytDance** [comment]
> you need to actually put the real path to the checkpoint and image file path

I did that in another script called test.py but I kept getting a different error  
```
Traceback (most recent call last):
  File "<...>\lsun-room-master\test.py", line 59, in <module>
    qq()
  File "<...>\lsun-room-master\test.py", line 34, in qq
    predictor = Predictor(weight)
                ^^^^^^^^^^^^^^^^^
  File "<...>\lsun-room-master\test.py", line 16, in __init__
    self.model = core.LayoutSeg.load_from_checkpoint(weight_path, backbone='resnet101')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<...>\lsun-room-master\env\Lib\site-packages\pytorch_lightning\utilities\model_helpers.py", line 125, in wrapper
    return self.method(cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<...>\lsun-room-master\env\Lib\site-packages\pytorch_lightning\core\module.py", line 1581, in load_from_checkpoint
    loaded = _load_from_checkpoint(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "<...>\lsun-room-master\env\Lib\site-packages\pytorch_lightning\core\saving.py", line 63, in _load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=map_location)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<...>\lsun-room-master\env\Lib\site-packages\lightning_fabric\utilities\cloud_io.py", line 60, in _load
    return torch.load(
           ^^^^^^^^^^^
  File "<...>\lsun-room-master\env\Lib\site-packages\torch\serialization.py", line 1384, in load
    return _legacy_load(
           ^^^^^^^^^^^^^
  File "<...>\lsun-room-master\env\Lib\site-packages\torch\serialization.py", line 1628, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, '\xff'.
```

test.py  is the same function as image() from demo.py but with paths hard coded in it

```
path="lsun-room-master/checkpoint/model_retrained.ckpt"
    weight = "lsun-room-master/test/img1.jpg" #just one image from the data as a test
    image_size = 320
```

**Comment by BytDance** [comment]
Thanks , I fixed it
